[package]
name = "odd_is_odd"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

description = "A very (not) safe library to check if a number is odd. Based on cve-rs. "
license = "Unlicense"
repository = "https://github.com/residualentropy/odd_is_odd"
readme = "README.md"

[dependencies]
